// The one place the app gets data from.
// Screens import from here, never from data/mock/ directly.
// To switch to real data, change this file only.

import demo from "@/data/mock/barrier-brain.json";
import sampleTgs from "@/data/mock/tgs/swanston-st-closure.webp";
import type { TgsAnalysis } from "@/lib/tgs-analysis";

export const sampleTgsUrl = sampleTgs.src;

// Claude reads the TGS for real. With no upload, it reads the sample Swanston St TGS.
export async function analyseTgs(file: File | undefined, signal?: AbortSignal): Promise<TgsAnalysis> {
  const upload = file ?? new File([await (await fetch(sampleTgs.src, { signal })).blob()], demo.tgs.fileName, { type: "image/webp" });
  const body = new FormData();
  body.append("file", upload);
  const response = await fetch("/api/analyse-tgs", { method: "POST", body, signal });
  const result = await response.json().catch(() => ({ error: "The analysis failed. Try again." }));
  if (!response.ok) throw new Error(result.error);
  return result.analysis;
}

// Numeric results are fixed demo fixtures, never generated by an LLM.
export function getAssessmentData() {
  const m = demo.analysis.metrics;
  return {
    ...demo,
    impactSummary: [
      { id: "traffic", label: "Traffic", severity: demo.analysis.severity.traffic, description: `Estimated queue length peaks at ${m.queueLengthM} m at ${m.queuePeakTime}.` },
      { id: "pedestrians", label: "Pedestrian access", severity: demo.analysis.severity.pedestrians, description: `Temporary route adds ${m.pedestrianDetourM} m and crosses one vehicle access point.` },
      { id: "transport", label: "Public transport", severity: demo.analysis.severity.transport, description: demo.explanations.transport },
      { id: "safety", label: "Site safety", severity: demo.analysis.severity.safety, description: demo.explanations.safety },
    ],
  };
}

export type AssessmentData = ReturnType<typeof getAssessmentData>;
export type Project = AssessmentData["projects"][number];
export type ImpactMetric = AssessmentData["impactSummary"][number];
