// The one place the app gets data from.
// Screens import from here, never from data/mock/ directly.
// To switch to real data, change this file only.

import demo from "@/data/mock/barrier-brain.json";

// Numeric results are fixed demo fixtures, never generated by an LLM.
export function getAssessmentData() {
  const m = demo.analysis.metrics;
  return {
    ...demo,
    impactSummary: [
      { id: "traffic", label: "Traffic", severity: demo.analysis.severity.traffic, description: `Estimated queue length peaks at ${m.queueLengthM} m at ${m.queuePeakTime}.` },
      { id: "pedestrians", label: "Pedestrian access", severity: demo.analysis.severity.pedestrians, description: `Temporary route adds ${m.pedestrianDetourM} m and crosses one vehicle access point.` },
      { id: "transport", label: "Public transport", severity: demo.analysis.severity.transport, description: demo.explanations.transport },
      { id: "safety", label: "Site safety", severity: demo.analysis.severity.safety, description: demo.explanations.safety },
    ],
  };
}

export type AssessmentData = ReturnType<typeof getAssessmentData>;
export type Project = AssessmentData["projects"][number];
export type ImpactMetric = AssessmentData["impactSummary"][number];
